TesisImp/AMCE/urls.py
from django.contrib import admin
from django.urls import include, path

#se agrega para heroku
#from django.conf import settings 
#from django.conf.urls.static import static

# Views
from AMCE import views

app_name = "AMCE"
urlpatterns = [
# URLS COMPARTIDAS
path('', views.index, name = 'index'),
path('registro/', views.registro, name = 'registro'),
path('bienvenida/', views.bienvenida, name = 'bienvenida'),
# URLS ESTUDIANTE
path('MG1/', views.MG1, name = 'MG1'),
path('crear/', views.MG1, name = 'crear'),
path('MG1/Grupo/<str:codigo>', views.PaginaAlumnoTema, name = 'PaginaAlumnoTema'),
path('MG1/UnirseGrupo/', views.AlumnoUnirseGrupo, name = 'AlumnoUnirseGrupo'),
path('MG1/Grupo/<str:codigo>/<str:tema>', views.PaginaActividadAlumno, name = 'PaginaActividadAlumno'),
path('MG1/Grupo/<str:codigo>/<str:tema>/PreguntaInicial', views.postPreguntaInicial, name = 'postPreguntaInicial'),
path('MG1/Grupo/<str:codigo>/<str:tema>/PreguntaInicial/Feed', views.feed, name = 'feed'), 
path('MG1/Grupo/<str:codigo>/<str:tema>/PreguntaInicial/FeedPreguntaInicial', views.feedPIHecha, name = 'feedPIHecha'),
# URLS PROFESOR
path('profesor/', views.profesor, name = 'profesor'),
path('profesor/MisGrupos/', views.ProfMisGrupos, name = 'ProfMisGrupos'),
path('profesor/CrearGrupo/', views.ProfCrearGrupo, name = 'ProfCrearGrupo'),
path('profesor/Grupo/<str:codigo>', views.ProfPaginaGrupo, name = 'ProfPaginaGrupo'),
path('profesor/Grupo/<str:codigo>/CrearEquipo', views.ProfCrearEquipo, name = 'ProfCrearEquipo'),
path('profesor/Grupo/<str:codigo>/Equipo/<int:equipo>', views.ProfPaginaEquipo, name = 'ProfPaginaEquipo'),
path('profesor/Grupo/<str:codigo>/AsignarTema', views.ProfAsignarTemaGrupo, name = 'ProfAsignarTemaGrupo'),
path('profesor/Grupo/<str:codigo>/<int:tema>', views.ProfTemaAsignado, name = 'ProfTemaAsignado'),
path('profesor/MisTemas/', views.ProfMisTemas, name = 'ProfMisTemas'),
path('profesor/CrearTema/', views.ProfCrearTema, name = 'ProfCrearTema')
]

TesisImp/TesisImp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
#Importamos las vistas de la aplicación django AMCE
from AMCE import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path("", include("AMCE.urls")),
    path('accounts/', include('django.contrib.auth.urls'))
]

urlpatterns += staticfiles_urlpatterns()

TesisImp/AMCE/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
#Heredo del userCreationForm que viene en django
class CustomUserCreationForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', "first_name", "last_name", "email", "password1", "password2"]

class CodeForm(forms.ModelForm):
	code = forms.CharField(label='Ingresa el código de la clase', widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu respuesta'}))

class FormActividadPI(forms.Form):
	contenido = forms.CharField(label='', max_length = 500, widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))


class PostPreguntaInicial(forms.ModelForm):
	#Aqui se obtiene el campo de contenido de nuestro modelo Forms para Post
	content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':2, 'placeholder': 'Ingresa tu pregunta inicial'}))

	class Meta:
		model = Post
		fields = ['content']

""" FORMS PROFESOR """

class FormCrearGrupo(forms.Form):
	nombre = forms.CharField(label='Nombre del grupo', max_length = 350)
	materia = forms.CharField(label='Materia', max_length =110)
	institucion = forms.CharField(label='Institución', max_length = 350) 

class FormCrearTema(forms.Form):
	nombre = forms.CharField(label='Nombre del tema', max_length = 100)

class FormCrearEquipo(forms.Form):
	nombre = forms.CharField(label='Nombre del equipo',max_length=100)
	integrantes = forms.MultipleChoiceField(choices=User.objects.all().values_list('id', 'last_name'),widget=forms.SelectMultiple)
	def __init__(self,*args,**kwargs):
		codigo = ''
		if 'codigo' in kwargs.keys():
			codigo = kwargs.pop('codigo')
		super().__init__(*args, **kwargs)
		if codigo != '':
			print(codigo)
			inscritos = Inscribir.objects.filter(codigo_materia=codigo).values_list('user_id', flat=True)
			usuarios = User.objects.filter(id__in=inscritos).order_by('last_name','first_name').values_list('id','last_name','first_name')
			estudiantes = []
			for i in usuarios:
				estudiantes.append((i[0],i[1] + " " + i[2]))
			print(usuarios)
			self.fields['integrantes'].choices = estudiantes

class AsignarTemaGrupo(forms.Form):
	tema = forms.ChoiceField(label='Tema',choices=Temas.objects.all().values_list('id_tema','nombre'))
	equipos = forms.MultipleChoiceField(choices=Equipos.objects.all().values_list('id_equipo', 'nombre'),widget=forms.SelectMultiple)
	def __init__(self,*args,**kwargs):
		codigo = ''
		if 'codigo' in kwargs.keys():
			codigo = kwargs.pop('codigo')
		super().__init__(*args, **kwargs)
		if codigo != '':
			user_id = Grupos.objects.get(codigo=codigo).user_id
			temas = Temas.objects.filter(user_id=user_id).values_list('id_tema','nombre')
			equipos = Equipos.objects.filter(codigo_materia=codigo).values_list('id_equipo', 'nombre')
			self.fields['tema'].choices = temas
			self.fields['equipos'].choices = equipos

TesisImp/AMCE/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib.auth import authenticate, login
from django.template import RequestContext
from django.contrib.auth.models import User
from .models import *
from django.urls import reverse
#se importa para aumentar el contador de votos en feed
from django.db.models import F
import random
import string

"""
	VISTAS/FUNCIONES COMPARTIDAS
"""

def index(request):
	return render(request, "index.html")

def registro(request):
	data = {
		'form': CustomUserCreationForm()
	}
	if request.method == "POST":
		formulario = CustomUserCreationForm(data=request.POST)
		if formulario.is_valid():
			usuario = formulario.save()
			usuario.save()
			user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])

			login(request,user)
			messages.success(request, "Registro exitoso, inicia sesión")
			return redirect(to="AMCE:bienvenida")
		data["form"] = formulario
	return render(request,'registration/registro.html',data)

def bienvenida(request):
	return render(request,"registration/bienvenida.html")

"""
	VISTAS/FUNCIONES DE ESTUDIANTE
"""

def alumno(request):
	current_user = get_object_or_404(User, pk=request.user.pk)
	usuarioTipo = UserType(userType=current_user,flag=1)
	usuarioTipo.save()
	return render(request,"estudiante/SelEquipo.html")

def AlumnoUnirseGrupo(request):
	inscribir = Inscribir()
	current_user = get_object_or_404(User, pk=request.user.pk)
	a = request.POST
	args = {'form': a}
	if request.method == 'POST':
		print(a)
		codigo_ingresado = request.POST.get("new")
		repetido = Inscribir.objects.filter(user_id=current_user,codigo_materia=codigo_ingresado)
		try:
			# Your code goes here
			inscribir.codigo_materia = Grupos.objects.get(codigo = request.POST.get("new"))
			if repetido.exists():
				print("Ya estas inscrito en este grupo")
				messages.add_message(request, messages.INFO, 'Ya estas inscrito')
				return redirect(to="AMCE:MG1")
			else:
				codigo_clase = Inscribir(user_id=current_user,codigo_materia=inscribir.codigo_materia)
				#inscribir.save()
				messages.add_message(request, messages.INFO, 'Grupo añadido')
				codigo_clase.save()
				return redirect(to="AMCE:MG1")
		except Grupos.DoesNotExist:
   			# Handle error here
   			print("ingresa un código valido")
   			messages.error(request, 'Ingresa un código valido')
   			return redirect(to="AMCE:MG1")
	return render(request,"estudiante/crear.html",args)

@login_required
def MG1(request):
	#Muestro las Grupos asignadas al ID del usuario actual en la página html
	code = Inscribir.objects.filter(user_id_id=request.user.pk)
	current_user = get_object_or_404(User, pk=request.user.pk)
	usuarioTipo = UserType.objects.filter(userType=current_user,flag=2)

	if(usuarioTipo):
		print("Eres maestro")
		return redirect(to="AMCE:ProfMisGrupos")
	else:
		usuarioTipoAlumno = UserType.objects.filter(userType=current_user,flag=1)
		if(usuarioTipoAlumno.exists()):
			print("Eres estudiante")
		else:
			usuarioTipo2 = UserType(userType=current_user,flag=1)
			usuarioTipo2.save()
	args = {'code':code}
	return render(request,"estudiante/SelEquipo.html",args)

def PaginaActividadAlumno(request, tema, codigo):
	
	current_user = get_object_or_404(User, pk=request.user.pk)
	'''
	pertenece = Pertenecer.objects.filter(user_id=current_user)
	equipo = Equipos.objects.get(codigo_materia=codigo) 
	asignar = Asignar.objects.filter(id_equipo=equipo.id_equipo)
	'''
	ids_equipos_relacionados_usuario = Pertenecer.objects.filter(user_id=current_user).values_list('id_equipo', flat=True)
	ids_equipos_relacionados_grupo = Equipos.objects.filter(codigo_materia=codigo, id_equipo__in=ids_equipos_relacionados_usuario)
	ids_temas = Asignar.objects.filter(id_equipo__in=ids_equipos_relacionados_grupo).values_list('id_tema', flat=True)
	temas = Temas.objects.filter(id_tema__in=ids_temas)

	return render(request, 'estudiante/Actividad.html',{'tema':tema, 'codigo':codigo, 'ids_temas':ids_temas.first()})

def PaginaAlumnoTema(request, codigo):
	
	current_user = get_object_or_404(User, pk=request.user.pk)
	grupo = Grupos.objects.filter(codigo=codigo)
	#Saco los usuarios relacionados a un equipo
	ids_equipos_relacionados_usuario = Pertenecer.objects.filter(user_id=current_user).values_list('id_equipo', flat=True)
	#saco los equipos relacionados a una materia (código)
	ids_equipos_relacionados_grupo = Equipos.objects.filter(codigo_materia=codigo, id_equipo__in=ids_equipos_relacionados_usuario)
	print(ids_equipos_relacionados_grupo)
	#saco los temas relacionados a los equipos del grupo de la materia
	ids_temas = Asignar.objects.filter(id_equipo__in=ids_equipos_relacionados_grupo).values_list('id_tema', flat=True)
	print(ids_temas)
	temas = Temas.objects.filter(id_tema__in=ids_temas)


	return render(request, 'estudiante/PaginaAlumnoTema.html', {'codigo':codigo ,'grupo':grupo.first(), 'temas':temas})

def postPreguntaInicial(request, tema ,codigo):
	current_user = get_object_or_404(User, pk=request.user.pk)
	tema_actual = Temas.objects.filter(nombre = tema).values_list('id_tema', flat=True)
	tema_actual_intancia = Temas.objects.get(id_tema__in=tema_actual)
	ids_equipos_relacionados_usuario = Pertenecer.objects.filter(user_id=current_user).values_list('id_equipo', flat=True)
	ids_equipos_relacionados_grupo = Equipos.objects.get(codigo_materia=codigo, id_equipo__in=ids_equipos_relacionados_usuario)
	print(ids_equipos_relacionados_grupo.id_equipo)
	if request.method == 'POST':
		form = FormActividadPI(request.POST)
		if form.is_valid():
			nueva_actividad = Actividad(contenido= form.cleaned_data['contenido'],
			 							pasoMG = 1.1,
			 							id_tema_id=Temas.objects.get(nombre=tema).id_tema,
			 							user=current_user)
			messages.add_message(request, messages.INFO, 'Respuesta capturada')
			nueva_actividad.save()
			nueva_hace = Hace(id_equipo_id= ids_equipos_relacionados_grupo.id_equipo,
								id_actividad_id=nueva_actividad.id_actividad,
								id_tema_id=Temas.objects.get(nombre=tema).id_tema)
			nueva_hace.save()
			return redirect('AMCE:feed' , codigo=codigo, tema=tema)
	else:
		form = FormActividadPI()
	return render(request, 'estudiante/PreguntaInicial.html', {'form': form, 'codigo':codigo, 'tema':tema})

def feed(request, tema, codigo):
	current_user = get_object_or_404(User, pk=request.user.pk)
	ids_equipos_relacionados_usuario = Pertenecer.objects.filter(user_id=current_user).values_list('id_equipo', flat=True)
	ids_equipos_relacionados_grupo = Equipos.objects.filter(codigo_materia=codigo, id_equipo__in=ids_equipos_relacionados_usuario)
	#Se obtiene el id del tema actual 
	prueba2 = Temas.objects.filter(nombre=tema).values_list('id_tema', flat=True)
	ids_equipo_relacionado_tema = Temas.objects.get(id_tema__in=prueba2)
	#Se obtiene el equipo relacionado al usuario actual con el tema actual, esto para sacar el id de equipo
	id_equipo_relacionado_tema_count = Asignar.objects.get(id_equipo__in=ids_equipos_relacionados_usuario, id_tema=ids_equipo_relacionado_tema)
	#Se muestra equipo en tema actual
	muestra_equipo = Pertenecer.objects.filter(id_equipo_id=id_equipo_relacionado_tema_count.id_equipo).count()
	print(muestra_equipo)

	hace_equipo = Hace.objects.filter(id_equipo__in=ids_equipos_relacionados_grupo, id_tema=ids_equipo_relacionado_tema)
	print(hace_equipo.count())

	if muestra_equipo == hace_equipo.count():
		return redirect('AMCE:feedPIHecha' , codigo=codigo, tema=tema)
	else:
		print("No todos han hecho esta actividad")
	return render(request, 'estudiante/feed.html', {'hace_equipo':hace_equipo, 'codigo':codigo, 'tema':tema})

def feedPIHecha(request, tema, codigo):
	current_user = get_object_or_404(User, pk=request.user.pk)
	ids_equipos_relacionados_usuario = Pertenecer.objects.filter(user_id=current_user).values_list('id_equipo', flat=True)
	ids_equipos_relacionados_grupo = Equipos.objects.filter(codigo_materia=codigo, id_equipo__in=ids_equipos_relacionados_usuario)
	#Se obtiene el id del tema actual 
	prueba2 = Temas.objects.filter(nombre=tema).values_list('id_tema', flat=True)
	ids_equipo_relacionado_tema = Temas.objects.get(id_tema__in=prueba2)
	#Se obtiene el equipo relacionado al usuario actual con el tema actual, esto para sacar el id de equipo
	id_equipo_relacionado_tema_count = Asignar.objects.get(id_equipo__in=ids_equipos_relacionados_usuario, id_tema=ids_equipo_relacionado_tema)
	#Se muestra equipo en tema actual
	hace_equipo = Hace.objects.filter(id_equipo__in=ids_equipos_relacionados_grupo, id_tema=ids_equipo_relacionado_tema)
	id_tema_voto = Temas.objects.get(nombre=tema).id_tema

	if request.method == 'POST':
		voto = request.POST.get("preguntaInicial")
		agregar_voto = Actividad.objects.filter(user=current_user, id_tema_id=id_tema_voto).update(voto=F('voto')+1)
		return redirect('AMCE:comentaPreguntaInicial', codigo=codigo, tema=tema)

	return render(request, 'estudiante/FeedPreguntaInicialHecha.html', {'hace_equipo':hace_equipo, 'codigo':codigo, 'tema':tema})

def comentaPreguntaInicial(request, tema, codigo):
	if request.method == 'POST':
		form = FormComentarPI(request.POST)
		if form.is_valid():
			print("es valido el form")
	else:
		form = FormComentarPI()

	return render(request, "estudiante/ComentarPreguntaInicial.html",{'form': form})

"""
	VISTAS/FUNCIONES DE PROFESOR
"""

def esProfesor(request):
	current_user = get_object_or_404(User, pk=request.user.pk)
	usuarioTipo = UserType.objects.filter(userType=current_user,flag=2)
	if( usuarioTipo ):
		return true
	else:
		return false

def profesor(request):
	current_user = get_object_or_404(User, pk=request.user.pk)
	usuarioTipo2 = UserType(userType=current_user,flag=2)
	usuarioTipo2.save()
	return redirect(to="AMCE:ProfMisGrupos")

@login_required
def ProfMisGrupos(request):
	#Se muestran los Grupos asignados al ID del usuario actual

TesisImp/AMCE/templates/profesor/AsignarTemaGrupo.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/multiselect.css'%}"/>
    <link rel="stylesheet" href="{% static 'css/AsignarTemaGrupo.css'%}"/>
    <script src="{%static 'js/multiselect.min.js' %}"></script>
{% endblock %}


{% block title %}
    AMCE - Asignar Tema
{% endblock %}

{% block header_ctxt %}
    <a class="navbar-brand" href="{% url 'AMCE:ProfPaginaGrupo' codigo=codigo %}"><i style="color: white;" class="bi bi-x-lg"></i></a>
    <div class="nav-bar-title navbar-brand" href="">Asignar Tema</div>
{% endblock %}

{% block button_content %}
    Asignar
{% endblock %}

{% block scripts %}
    <script>
        document.multiselect('#id_equipos');
    </script>
{% endblock %}

TesisImp/AMCE/templates/profesor/CrearEquipo.html
{% extends "profesor/base_formpage.html" %}

{% load static %}

{% block extra-css %}
    <link rel="stylesheet" href="{% static 'css/multiselect.css'%}"/>
    <script src="{%static 'js/multiselect.min.js' %}"></script>
{% endblock %}

{% block title %}
    AMCE - Crear Equipo
{% endblock %}

{% block header_ctxt %}
    <a class="navbar-brand" href="{% url 'AMCE:ProfPaginaGrupo' codigo=codigo %}"><i style="color: white;" class="bi bi-x-lg"></i></a>
    <div class="nav-bar-title navbar-brand" href="">Crear Equipo</div>
{% endblock %}

{% block button_content %}
    Guardar
{% endblock %}

{% block scripts %}
    <script>
        document.multiselect('#id_integrantes');
    </script>
{% endblock %}

TesisImp/AMCE/templates/profesor/CrearGrupo.html
{% extends "profesor/base_formpage.html" %}

{% load static %}


{% block title %}
    AMCE - Crear Grupo
{% endblock %}

{% block header_ctxt %}
    <a class="navbar-brand" href="{% url 'AMCE:ProfMisGrupos' %}"><i style="color: white;" class="bi bi-x-lg"></i></a>
    <div class="nav-bar-title navbar-brand" href="">Crear Grupo</div>
{% endblock %}

{% block button_content %}
    Guardar Grupo
{% endblock %}

TesisImp/AMCE/templates/profesor/CrearTema.html
{% extends "profesor/base_formpage.html" %}

{% load static %}


{% block title %}
    AMCE - Crear Tema
{% endblock %}

{% block header_ctxt %}
    <a class="navbar-brand" href="{% url 'AMCE:ProfMisTemas' %}"><i style="color: white;" class="bi bi-x-lg"></i></a>
    <div class="nav-bar-title navbar-brand" href="">Crear Tema</div>
{% endblock %}

{% block button_content %}
    Guardar Tema
{% endblock %}

TesisImp/AMCE/templates/profesor/MisGrupos.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}


{% block title %}
    AMCE - Mis Grupos
{% endblock %}

{% block header_ctxt %}
    <div class="nav-bar-title navbar-brand">Mis grupos</div>
    <a class="nav-bar-btn"  href="{% url 'AMCE:ProfCrearGrupo' %}" id="crear_grupo"> <img src="{% static 'assets/images/bt_grupos.png'%}"></a>
{% endblock %}

{% block navbar_ctxt %}
    <li class="nav-item active"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisGrupos' %}">Mis Grupos</a></li>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisTemas' %}">Mis Temas</a></li>
{% endblock %}

{% block inner_content %}
    <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
        <!--Grupos-->
        {% for g in grupos %}
        <div class="col mb-3">
            
                <div class="grupo-card card h-100" >
                    <!-- Detalles del grupo -->
                    <div class="card-body p-3">
                        <a href="{% url 'AMCE:ProfPaginaGrupo' codigo=g.codigo %}">
                            <b>Grupo: </b>{{g.grupo}}<br>
                            <b>Materia: </b>{{g.materia}}<br>
                            <b>Institución: </b>{{g.institucion}}<br>
                            <br>
                            <b>Código: </b>{{g.codigo}}
                        </a>
                        <img class="btn-editar float-right" src="{% static 'assets/images/bt_editar.png'%}">
                    </div>
                </div>
            
        </div>
        {% endfor %}
    </div>
{% endblock %}

TesisImp/AMCE/templates/profesor/MisTemas.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}


{% block title %}
    AMCE - Mis Temas
{% endblock %}

{% block header_ctxt %}
    <div class="nav-bar-title navbar-brand">Mis temas</div>
    <a class=" btn btn-outline-light"  href="{% url 'AMCE:ProfCrearTema' %}" id="crear_tema" style="color: white;">Crear</a>
{% endblock %}

{% block navbar_ctxt %}
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisGrupos' %}">Mis Grupos</a></li>
    <li class="nav-item active"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisTemas' %}">Mis Temas</a></li>
{% endblock %}

{% block inner_content %}
    <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
        <!--Temas-->
        {% for t in temas %}
        <div class="col mb-3">
            <a href="#">
                <div class="card h-100" >
                    <!-- Detalles del tema -->
                    <div class="card-body p-4">
                        <div>
                            <h4 class="fw-bolder">{{t.nombre}}</h4>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

TesisImp/AMCE/templates/profesor/PaginaEquipo.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}


{% block title %}
    AMCE - {{ equipo_nombre }}
{% endblock %}

{% block header_ctxt %}
    <div class="nav-bar-title navbar-brand">{{ equipo_nombre }}</div>
    <a class=""></a>
{% endblock %}

{% block navbar_ctxt %}
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisGrupos' %}">Mis Grupos</a></li>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisTemas' %}">Mis Temas</a></li>
{% endblock %}

{% block inner_content %}
    <h3>Integrantes:</h3>
    </br>
    <!--integrantes-->
    {% for i in integrantes %}
    <div>
        <h4>{{ i }}</h4>
    </div>
    </br>
    {% endfor %}
{% endblock %}

TesisImp/AMCE/templates/profesor/PaginaGrupo.html
{% extends "profesor/base_mainpage.html" %}

{% load static %}

{% block title %}
    AMCE - {{ grupo.grupo }}
{% endblock %}

{% block header_ctxt %}
<div class="nav-bar-title navbar-brand"><p class="small-text">{{ grupo.materia }}</p></div>
<a class=""></a>
{% endblock %}

{% block navbar_ctxt %}
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisGrupos' %}">Mis Grupos</a></li>
    <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'AMCE:ProfMisTemas' %}">Mis Temas</a></li>
{% endblock %}

{% block inner_content %}
    <h3 class="mb-3">{{ grupo.grupo }} - {{ grupo.institucion }}</h3>
    <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="temas-tab" data-bs-toggle="tab" data-bs-target="#temas" type="button" role="tab" aria-controls="temas" aria-selected="true">Temas</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="equipos-tab" data-bs-toggle="tab" data-bs-target="#equipos" type="button" role="tab" aria-controls="equipos" aria-selected="false">Equipos</button>
        </li>
    </ul>
    <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="temas" role="tabpanel" aria-labelledby="temas-tab">
            </br>
            </br>
            <a class=" btn btn-outline-dark btn-block"   href="{% url 'AMCE:ProfAsignarTemaGrupo' codigo=codigo %}" id="asignar_tema">Asignar Tema</a>
            </br>
            </br>
            <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
                {% for t in temas %}
                <div class="col mb-5">
                    <a href="{% url 'AMCE:ProfTemaAsignado' codigo=codigo tema=t.id_tema%}">
                        <div class="card h-100" >
                            <!-- Detalles del tema -->
                            <div class="card-body p-4">
                                <div>
                                    <h4 class="fw-bolder">{{t.nombre}}</h4>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="tab-pane fade" id="equipos" role="tabpanel" aria-labelledby="equipos-tab">
            </br>
            </br>
            <a class=" btn btn-outline-dark btn-block"   href="{% url 'AMCE:ProfCrearEquipo' codigo=codigo %}" id="crear_equipo">Crear Equipo</a>
            </br>
            </br>
            <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-2 row-cols-xl-3 justify-content">
                {% for e in equipos %}
                <div class="col mb-3">
                    <a href="{% url 'AMCE:ProfPaginaEquipo' codigo=codigo equipo=e.id_equipo%}">
                        <div class="card h-100">
                            <div class="card-body p-4">
                                <div>
                                    <h4 class="fw-bolder">{{ e.nombre }}</h4>
                                </div>
                            </div>
                        </div>
                    </a>
                    
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}